export const config = {
  sponsorshipUrl: "https://ko-fi.com/iceflake0",
  vendingMachineColor: "#ff4d4f",
  "projects": [
    {
      "id": "10",
      "name": "TimeStitch",
      "description": "一个轻量的时间管理工具",
      "website": "https://foroneice.github.io/TimeStitch/",
      "topics": [],
      "production_date": "2025-10-14T12:34:20Z",
      "version": "4",
      "repo_url": "https://github.com/ForOneIce/TimeStitch",
      "is_private": false,
      "stars": 0,
      "language": "HTML",
      "created_at": "2025-10-14T10:27:26Z",
      "updated_at": "2025-12-30T07:34:03Z"
    },
    {
      "id": "11",
      "name": "web3-solidity-guide-cn",
      "description": "30天Solidity入门挑战，智能合约开发指南🧭 Web3 Compass 中文学习站",
      "website": "https://foroneice.github.io/web3-solidity-guide-cn/",
      "topics": [
        "guidebook",
        "solidity",
        "web3"
      ],
      "production_date": "2025-10-14T21:06:15Z",
      "version": "14",
      "repo_url": "https://github.com/ForOneIce/web3-solidity-guide-cn",
      "is_private": false,
      "stars": 13,
      "language": "Unknown",
      "created_at": "2025-10-14T21:10:04Z",
      "updated_at": "2026-04-01T01:51:59Z"
    },
    {
      "id": "12",
      "name": "BugBountyToolsMap",
      "description": "🧭 基于可视化地图和知识卡片的漏洞赏金工具参考 — 学习、贡献和探索生态系统。",
      "website": "https://huntermap.space/",
      "topics": [],
      "production_date": "2025-10-23T15:00:18Z",
      "version": "5",
      "repo_url": "https://github.com/ForOneIce/BugBountyToolsMap",
      "is_private": true,
      "stars": 0,
      "language": "JavaScript",
      "created_at": "2025-11-03T02:58:35Z",
      "updated_at": "2026-04-04T06:44:29Z"
    },
    {
      "id": "15",
      "name": "CoFocus",
      "description": "A cozy AI-supervised study room",
      "website": "https://co-focus-lake.vercel.app",
      "topics": [],
      "production_date": "2025-11-22T15:23:11Z",
      "version": "14",
      "repo_url": "https://github.com/ForOneIce/CoFocus",
      "is_private": true,
      "stars": 0,
      "language": "TypeScript",
      "created_at": "2025-11-22T15:23:09Z",
      "updated_at": "2025-12-30T07:29:08Z"
    },
    {
      "id": "17",
      "name": "MathMusic",
      "description": "The Sound of Numbers",
      "website": "https://math-music.vercel.app/",
      "topics": [],
      "production_date": "2025-11-25T17:32:08Z",
      "version": "7",
      "repo_url": "https://github.com/ForOneIce/MathMusic",
      "is_private": true,
      "stars": 0,
      "language": "TypeScript",
      "created_at": "2025-11-25T17:32:06Z",
      "updated_at": "2025-12-19T05:30:01Z"
    },
    {
      "id": "18",
      "name": "VideoLingoAI",
      "description": "VideoLingoAI",
      "website": "https://video-lingo-ai.vercel.app",
      "topics": [],
      "production_date": "2025-12-05T14:18:27Z",
      "version": "24",
      "repo_url": "https://github.com/ForOneIce/VideoLingoAI",
      "is_private": true,
      "stars": 0,
      "language": "TypeScript",
      "created_at": "2025-12-05T14:18:25Z",
      "updated_at": "2025-12-30T07:32:10Z"
    },
    {
      "id": "21",
      "name": "VisionFocusHours",
      "description": "VisionFocus Hours 是一个结合愿景板（Vision Board）与时间追踪的DApp，帮助用户通过可视化愿望和记录专注时间来显化未来。用户可以通过冥想引导设定年度愿景，制作个性化的愿景板，并通过投币（记录专注时间）的方式逐步显化愿望。当愿望实现时，可以生成年度NFT作为纪念。",
      "website": "https://vision-focus-hours.vercel.app",
      "topics": [
        "web3-dapp"
      ],
      "production_date": "2026-01-03T03:18:30Z",
      "version": "7",
      "repo_url": "https://github.com/ForOneIce/VisionFocusHours",
      "is_private": false,
      "stars": 0,
      "language": "HTML",
      "created_at": "2026-01-03T03:18:30Z",
      "updated_at": "2026-03-01T09:00:52Z"
    },
    {
      "id": "31",
      "name": "solidity-bootcamp-pass",
      "description": "基于网页的编辑器，用于生成可定制的训练营通行证。适用于 Web3 教育项目。",
      "website": "https://solidity-bootcamp-pass.vercel.app/",
      "topics": [],
      "production_date": "2026-02-26T06:44:44Z",
      "version": "28",
      "repo_url": "https://github.com/ForOneIce/solidity-bootcamp-pass",
      "is_private": false,
      "stars": 0,
      "language": "TypeScript",
      "created_at": "2026-02-26T06:44:41Z",
      "updated_at": "2026-03-02T16:57:25Z"
    },
    {
      "id": "33",
      "name": "pr-review-tool",
      "description": "用于共学活动的助教pr批改工具。自动获取学员 PR，检查每日打卡，统计通关情况，并提供便捷的代码批注界面。",
      "website": "https://pr-review-tool-pink.vercel.app",
      "topics": [],
      "production_date": "2026-03-02T12:57:37Z",
      "version": "8",
      "repo_url": "https://github.com/ForOneIce/pr-review-tool",
      "is_private": false,
      "stars": 0,
      "language": "TypeScript",
      "created_at": "2026-03-02T12:55:12Z",
      "updated_at": "2026-03-30T04:42:28Z"
    },
    {
      "id": "34",
      "name": "Co-LearningChallenge",
      "description": "共学营挑战日历",
      "website": "https://co-learning-challenge.vercel.app/",
      "topics": [],
      "production_date": "2026-03-09T20:20:35Z",
      "version": "9",
      "repo_url": "https://github.com/ForOneIce/Co-LearningChallenge",
      "is_private": false,
      "stars": 0,
      "language": "TypeScript",
      "created_at": "2026-03-09T20:17:55Z",
      "updated_at": "2026-04-04T05:25:56Z"
    },
    {
      "id": "36",
      "name": "hunter-handbook",
      "description": "🦉 A magical onboarding handbook for aspiring bug bounty hunters. From owl invitation to first bounty—your complete guide.",
      "website": "https://hunter-handbook.vercel.app",
      "topics": [],
      "production_date": "2026-03-18T20:59:40Z",
      "version": "1",
      "repo_url": "https://github.com/ForOneIce/hunter-handbook",
      "is_private": true,
      "stars": 0,
      "language": "TypeScript",
      "created_at": "2026-03-18T20:51:52Z",
      "updated_at": "2026-03-18T21:02:52Z"
    },
    {
      "id": "37",
      "name": "flowpage",
      "description": "个人沉浸式阅读器 \"弱水三千，只取一瓢饮\" 一次只专注读完一本书，在知识的溪流中安静冥想。",
      "website": "https://flowpage-5zde.vercel.app",
      "topics": [],
      "production_date": "2026-03-21T09:01:37Z",
      "version": "9",
      "repo_url": "https://github.com/ForOneIce/flowpage",
      "is_private": false,
      "stars": 0,
      "language": "TypeScript",
      "created_at": "2026-03-21T09:01:35Z",
      "updated_at": "2026-03-21T10:50:35Z"
    },
    {
      "id": "38",
      "name": "SourceMapLeak",
      "description": "一个 Source Map 泄露漏洞的科普、检测与安全防护平台",
      "website": "https://source-map-leak.vercel.app",
      "topics": [],
      "production_date": "2026-03-31T21:11:21Z",
      "version": "9",
      "repo_url": "https://github.com/ForOneIce/SourceMapLeak",
      "is_private": false,
      "stars": 0,
      "language": "TypeScript",
      "created_at": "2026-03-31T20:44:03Z",
      "updated_at": "2026-03-31T22:11:03Z"
    },
    {
      "id": "40",
      "name": "WWW6.5-Memory",
      "description": "为0xHerstory Web3 6.5期Solidity共学营打造的结业纪念站点。",
      "website": "https://www-6-5-memory.vercel.app",
      "topics": [],
      "production_date": "2026-04-03T14:14:39Z",
      "version": "4",
      "repo_url": "https://github.com/ForOneIce/WWW6.5-Memory",
      "is_private": false,
      "stars": 0,
      "language": "TypeScript",
      "created_at": "2026-04-03T14:14:37Z",
      "updated_at": "2026-04-03T14:45:37Z"
    },
    {
      "id": "41",
      "name": "vibe-vending-machine",
      "description": "A playful portfolio showcase disguised as a  street-side beverage vending machine.",
      "website": "https://vibe-vending-machine.vercel.app",
      "topics": [],
      "production_date": "2026-04-06T15:46:56Z",
      "version": "5",
      "repo_url": "https://github.com/ForOneIce/vibe-vending-machine",
      "is_private": false,
      "stars": 0,
      "language": "TypeScript",
      "created_at": "2026-04-06T15:33:24Z",
      "updated_at": "2026-04-06T16:01:43Z"
    }
  ]
};
